services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
  frontend:
    build: ./crypto-index-fund-ui
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
